### ISSUE TITLE
Invalid code in session.go

### ISSUE THREAD

**Issue by chrisprobst** [ipfans/echo-session#12]
Latest commit just broke the entire library:

https://github.com/ipfans/echo-session/blob/master/session.go#L67

Your current head IS NOT compatible with echo v3. There is no Writer() function. Please fix and revert. Your lib is broken now!

CHECK:
https://github.com/labstack/echo/blob/master/response.go#L14

**Comment by ijust** [comment]
Latest commit is pre-release.
https://github.com/labstack/echo/releases

In stable latest release, it is compatible.
https://github.com/labstack/echo/blob/v3.0.3/response.go#L14

Fix this problem, Please not revert and set git tags for vendoring properly.

**Comment by ipfans** [comment]
I think it is a good point that golang need a package management tool. 😄 

If you use [glide](https://github.com/Masterminds/glide)(or other package management tool like [dep](https://github.com/golang/dep) ), please use ```v3.0.0-rc1``` instead of master branch.

**Comment by carynova** [comment]
to fix it just delete the '()'
`s := &session{name, rq, store, nil, false, rs.Writer}`

**Comment by meekmichael** [comment]
Could a v3.0.0-rc2 be made with this PR plus the current master with the Postgres session code in it?
