### ISSUE TITLE
cannot use rs.Writer (type func() http.ResponseWriter) as type http.ResponseWriter

### ISSUE THREAD

**Issue by ricardobiundo** [ipfans/echo-session#16]
I get the following error:

session.go:67:49: cannot use rs.Writer (type func() http.ResponseWriter) as type http.ResponseWriter in field value:
func() http.ResponseWriter does not implement http.ResponseWriter (missing Header method)

Any suggestions?
I'm using go version go1.10.1 linux/amd64

**Comment by ricardobiundo** [comment]
Maybe just adding parenthesis?

s := &session{name, rq, store, nil, false, rs.Writer()}
to
s := &session{name, rq, store, nil, false, rs.Writer}

**Comment by ipfans** [comment]
It seems like a new break change. I will be check this.

**Comment by ipfans** [comment]
@ricardobiundo  I checked the changes. It seems that you are using a outdated echo framework. If you want to use this library for older version, you should chose the version before v3.1.1(it contains a modification with newer echo framework).
