### ISSUE TITLE
Pool type error

### ISSUE THREAD

**Issue by ataklychev** [ipfans/echo-session#18]
I have error on compilation

vendor/github.com/ipfans/echo-session/redis_store.go:45:46: cannot use pool (type *"gitlab.com/intwt/front/vendor/github.com/gomodule/redigo/redis".Pool) as type *"gitlab.com/intwt/front/vendor/github.com/garyburd/redigo/redis".Pool in argument to redistore.NewRediStoreWithPool

... and find this issue - https://github.com/gin-contrib/sessions/issues/61
last release (https://github.com/boj/redistore/releases/tag/v1.2) not compatible, but v.1.2.1 not released

how to solve this problem ?

**Comment by ipfans** [comment]
If you are using vendor management toolkit(dep or others), you can change refer to master branch. Or just waiting for owner of redistore to release new version.
