### ISSUE TITLE
No session set options example

### ISSUE THREAD

**Issue by acidvertigo** [ipfans/echo-session#2]
i'm tryng to understand how to set the options for the session (path, maxage etc...) but with no success. Is possible to have an example for this?

**Comment by ipfans** [comment]
Options stores configuration for a session or session store. Fields are a subset of stdlib http.Cookie fields. So you can set values like http.Cookie.

This repo is working for echo.v1. if you want use session in echo.v2, I suggest to https://github.com/echo-contrib/sessions.

**Comment by acidvertigo** [comment]
understood thank you !
