### ISSUE TITLE
Handler clearance neglected?

### ISSUE THREAD

**Issue by 0x7061** [ipfans/echo-session#7]
In the gorilla/session description it states:

> Important Note: If you aren't using gorilla/mux, you need to wrap your handlers with context.ClearHandler as or else you will leak memory! An easy way to do this is to wrap the top-level mux when calling http.ListenAndServe:
http.ListenAndServe(":8080", context.ClearHandler(http.DefaultServeMux))

Echo is using an own router so I'm wondering if this middleware is already doing that to avoid memory leaks?

Source> http://www.gorillatoolkit.org/pkg/sessions

**Comment by ipfans** [comment]
This issue is be fixed, thanks for your report.
