### ISSUE TITLE
Create branches or tags for echo versions?

### ISSUE THREAD

**Issue by mmindenhall** [ipfans/echo-session#8]
Given that echo has changed a lot from v1 to v2, then from v2 to v3 (becoming more like v1), it might be good to tag the last commit to support v1 as "v1", and last commit to support v2 as "v2".

It would be even better (but more work) to create separate branches for each version, and apply any non-version specific changes or fixes to each.

**Comment by ipfans** [comment]
Thanks for your advice. I will make it happen ASAP.

**Comment by ipfans** [comment]
Now ipfans/echo-session works with branches and tags. 🍻
